# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03bffa2652b299ecf763c34c6598f0c4ef88008974d33921031e1cba974fc4130e74d58e8be77f431205bb6e13da5bb0d5cbae4da851a5d270630fee5b1ef75e

test:
  secret_key_base: 9ae00e34bfb2b8cc6fa43ff767c9f284ac3fa2d8b42ebcb66a1a6cc2b6e51ab512c991ff7cf944941103432db8eb8882d80cca914a468391c031bd5e5653566b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
